export class Symbols {
    symbols:any[] = [
        { "alias": "Arts Center", "name": "ARTSCENTER", "symbol": "palette", "source": "material" },
        { "alias": "Baseball or Softball Fields", "name": "BALLFIELDS", "symbol": "./assets/baseball-black-22.svg", "source": "nps" },
        { "alias": "Boat Rentals", "name": "BOATRENTALS", "symbol": "./assets/rowboating-black-22.svg", "source": "nps" },
        { "alias": "Bocce", "name": "BOCCE", "symbol": "hdr_strong", "source": "material" },
        { "alias": "BMX Track", "name": "BMXTRACK", "symbol": "./assets/motor-bike-trail-black-22.svg", "source": "nps" },
        { "alias": "Canoe Launch", "name": "CANOE", "symbol": "./assets/canoe-access-black-22.svg", "source": "nps" },
        { "alias": "Carousel", "name": "CAROUSEL", "symbol": "./assets/", "source": "nps" },
        { "alias": "Disc Golf", "name": "DISCGOLF", "symbol": "./assets/", "source": "nps" },
        { "alias": "Dog Park", "name": "DOGPARK", "symbol": "./assets/pets-off-leash-black-22.svg", "source": "nps" },
        { "alias": "Environmental Education Center", "name": "ENVCTR", "symbol": "school", "source": "material" },
        { "alias": "Fishing Access", "name": "FISHING", "symbol": "./assets/fishing-black-22.svg", "source": "nps" },
        { "alias": "Greenway Access", "name": "GREENWAYACCESS", "symbol": "./assets/trailhead-black-22.svg", "source": "nps" },
        { "alias": "Gymnasium", "name": "GYM", "symbol": "./assets/exercise-fitness-black-22.svg", "source": "nps" },
        { "alias": "Horseshoe Pit", "name": "HORSESHOE", "symbol": "./assets/", "source": "nps" },
        { "alias": "Inline Hockey", "name": "INLINESKATING", "symbol": "sports_hockey", "source": "material" },
        { "alias": "Kiddie Boats", "name": "BOATRIDE", "symbol": "./assets/sailing-black-22.svg", "source": "nps" },
        { "alias": "Library", "name": "LIBRARY", "symbol": "./assets/library-black-22.svg", "source": "nps" },
        { "alias": "Miniature Train", "name": "AMUSEMENTTRAIN", "symbol": "train", "source": "material" },
        { "alias": "Multipurpose Field", "name": "MULTIPURPOSEFIELD", "symbol": "./assets/", "source": "nps" },
        { "alias": "Outdoor Basketball", "name": "OUTDOORBASKETBALL", "symbol": "sports_basketball", "source": "material" },
        { "alias": "Picnic Shelter", "name": "PICNICSHELTER", "symbol": "./assets/picnic-shelter-black-22.svg", "source": "nps" },
        { "alias": "Playground", "name": "PLAYGROUND", "symbol": "./assets/playground-black-22.svg", "source": "nps" },
        { "alias": "Pool", "name": "POOL", "symbol": "./assets/swimming-black-22.svg", "source": "nps" },
        { "alias": "Recreation Center", "name": "COMMUNITYCENTER", "symbol": "people", "source": "material" },
        { "alias": "Neighborhood Center", "name": "NEIGHBORHOODCENTER", "symbol": "house", "source": "material" },
        { "alias": "Sand Volleyball", "name": "SANDVOLLEYBALL", "symbol": "./assets/volleyball-black-22.svg", "source": "nps" },
        { "alias": "Skate Park", "name": "SKATEPARK", "symbol": "./assets/skateboarding-black-22.svg", "source": "nps" },
        { "alias": "Tennis Center", "name": "TENNISCENTER", "symbol": "./assets/tennis-black-22.svg", "source": "nps" },
        { "alias": "Tennis Courts", "name": "TENNISCOURTS", "symbol": "./assets/tennis-black-22.svg", "source": "nps" },
        { "alias": "Theater", "name": "THEATER", "symbol": "./assets/theater-black-22.svg", "source": "nps" },
        { "alias": "Track", "name": "TRACK", "symbol": "directions_run", "source": "material" },
        { "alias": "Walking Trails", "name": "WALKINGTRAILS", "symbol": "./assets/walking-black-22.svg", "source": "nps" },
        { "alias": "Unique Space", "name": "UNIQUESP", "symbol": "./assets/", "source": "nps" },
        { "alias": "Handball", "name": "HANDBALL", "symbol": "sports_handball", "source": "material" },
        { "alias": "Active Adult Center", "name": "ACTIVE_ADULT", "symbol": "./assets/", "source": "nps" },
        { "alias": "Teen Center", "name": "TEEN", "symbol": "./assets/", "source": "nps" },
        { "alias": "Museum", "name": "MUSEUM", "symbol": "./assets/museum-black-22.svg", "source": "nps"}];
}



